# Generated by Django 4.2.6 on 2023-10-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conbud", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="song", name="album",),
        migrations.DeleteModel(name="Album",),
        migrations.DeleteModel(name="Musician",),
    ]
